name: multi_domain_secure_server
description: A SecureServerSocket that supports multiple domains with dynamic SecurityContext resolution.
version: 1.0.10
repository: https://github.com/gmpassos/multi_domain_secure_server

environment:
  sdk: ^3.5.0

false_secrets:
  ## Contains a `localhost` private key and certificate
  ## for tests/benchmarks of HTTPS connections:
  - test/localhost_cert.dart

dependencies:
  logging: ^1.3.0
  dependency_validator: ^4.1.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.10
  shelf: ^1.4.2
  async_benchmark: ^1.0.2

#dependency_overrides:
#  async_benchmark:
#    path: ../async_benchmark
