name: multi_domain_secure_server
description: A SecureServerSocket that supports multiple domains with dynamic SecurityContext resolution.
version: 1.0.8
repository: https://github.com/gmpassos/multi_domain_secure_server

environment:
  sdk: ^3.5.0

false_secrets:
  ## Contains a `localhost` private key for
  ## benchmark of HTTPS connections:
  - benchmark/shelf_benchmark.dart

dependencies:
  logging: ^1.3.0
  dependency_validator: ^4.1.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.9
  shelf: ^1.4.2
  async_benchmark: ^1.0.1

#dependency_overrides:
#  async_benchmark:
#    path: ../async_benchmark
