name: multi_domain_secure_server
description: A SecureServerSocket that supports multiple domains with dynamic SecurityContext resolution.
version: 1.0.2
repository: https://github.com/gmpassos/multi_domain_secure_server

environment:
  sdk: ^3.5.0

dependencies:
  logging: ^1.3.0
  dependency_validator: ^4.1.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.9
  shelf: ^1.4.2
