name: shelf_example
description: Example of `shelf` using `multi_domain_secure_server`.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  multi_domain_secure_server:
    path: ../../
  shelf: ^1.4.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
